In [2]:
#classwork Module 4b
from sklearn.datasets import load_wine

wine = load_wine()
print (wine)

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [3]:
#classwork Module 4b

#Import required libraries
import pandas as pd
import numpy as np
from sklearn.datasets import load_wine
from sklearn.linear_model import Perceptron         #model
from sklearn.model_selection import train_test_split     #trains, tests, splits
from sklearn.metrics import accuracy_score   #gives the cost function
from sklearn.metrics import confusion_matrix        #confusion matrix just for more analysis
wine = load_wine()         #method inside the dataset to load into wine
#View the iris data keys
wine.keys()           #allows you to see the keys of the iris dataset you want to load
#it is a key of dictionary of wine
wine.target_names
##Convert data and target into a data frame.
#Extract the First 100 Features
X = pd.DataFrame(data = wine.data[:100,:], columns = wine.feature_names)      #pandas to do processing to extract the first 100(60 for training, 30 for testing, 10 for ....)
X.head(100) #Inspect the features
#Target
y = pd.DataFrame(data=wine.target[:100], columns = ['wineType'])
y.head(100)
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Create a Perceptron classifier
mdlPercept = Perceptron()
# Train the classifier
mdlPercept.fit(X_train, y_train)
# Make predictions on the test set
y_pred = mdlPercept.predict(X_test)
# Calculate accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
#Generate the Confusion Matrix
print("Perceptron Confusion Matrix:\n",confusion_matrix(y_test, y_pred))

Accuracy: 0.85
Perceptron Confusion Matrix:
 [[12  1]
 [ 2  5]]


C:\Users\MELODY\anaconda3\envs\tensorflow\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [5]:
#classwork Module 4b

#Import required libraries
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import Perceptron         #model
from sklearn.model_selection import train_test_split     #trains, tests, splits
from sklearn.metrics import accuracy_score   #gives the cost function
from sklearn.metrics import confusion_matrix        #confusion matrix just for more analysis
breast_cancer = load_breast_cancer()         #method inside the dataset to load into wine
#View the iris data keys
breast_cancer.keys()           #allows you to see the keys of the iris dataset you want to load
#it is a key of dictionary of wine
breast_cancer.target_names
##Convert data and target into a data frame.
#Extract the First 100 Features
X = pd.DataFrame(data = breast_cancer.data[:123,:], columns = breast_cancer.feature_names)      
X.head(123) #Inspect the features
#Target
y = pd.DataFrame(data=breast_cancer.target[:123], columns = ['breastcancerType'])
y.head(123)
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Create a Perceptron classifier
mdlPercept = Perceptron()
# Train the classifier
mdlPercept.fit(X_train, y_train)
# Make predictions on the test set
y_pred = mdlPercept.predict(X_test)
# Calculate accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
#Generate the Confusion Matrix
print("Perceptron Confusion Matrix:\n",confusion_matrix(y_test, y_pred))

Accuracy: 0.96
Perceptron Confusion Matrix:
 [[18  1]
 [ 0  6]]


C:\Users\MELODY\anaconda3\envs\tensorflow\Lib\site-packages\sklearn\utils\validation.py:1300: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [21]:
#Assignment

import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# Load iris dataset
iris = load_iris()

# Extract the first 100 features
X = pd.DataFrame(data=iris.data[:100,:], columns=iris.feature_names)

# Target
y = pd.DataFrame(data=iris.target[:100], columns=['irisType'])

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert dataframes to numpy arrays
X_train = np.array(X_train)
X_test = np.array(X_test)
y_train = np.array(y_train)
y_test = np.array(y_test)

# Define and compile the model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, activation='sigmoid', input_shape=(X_train.shape[1],))
])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=10, batch_size=32, verbose=0)

# Evaluate the model
y_pred_proba = model.predict(X_test)
y_pred = (y_pred_proba > 0.5).astype(np.int32)

# Calculate accuracy of the classifier
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Generate the Confusion Matrix
print("Perceptron Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

C:\Users\MELODY\anaconda3\envs\tensorflow\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
Accuracy: 0.4
Perceptron Confusion Matrix:
 [[ 0 12]
 [ 0  8]]
